export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const ADD_DATA_REQUEST = 'ADD_DATA_REQUEST';
export const ADD_DATA_FAILURE = 'ADD_DATA_FAILURE';
export const ADD_DATA_SUCCESS = 'ADD_DATA_SUCCESS';

export const DELETE_DATA_REQUEST = 'DELETE_DATA_REQUEST';
export const DELETE_DATA_FAILURE = 'DELETE_DATA_FAILURE';
export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS';


export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';

export const GET_AUTHOR_SUCCESS = 'GET_AUTHOR_SUCCESS';
export const RESET_AUTHOR = 'RESET_AUTHOR';

